---
- hosts: "masters, workers"
  remote_user: <Your-User>
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh
  vars:
    kube_version: "<Version you want to install>"
  
  tasks:
   
   - name: Make the Swap inactive
     command: swapoff -a

   - name: Remove Swap entry from /etc/fstab.
     lineinfile:
       dest: /etc/fstab
       regexp: swap
       state: absent


   - name: Configure module for containerd
     shell: 
       cmd: |
        cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf 
        overlay 
        br_netfilter 
        EOF
        sudo modprobe overlay
        sudo modprobe br_netfilter
        cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf 
        net.bridge.bridge-nf-call-iptables  = 1 
        net.bridge.bridge-nf-call-ip6tables = 1 
        net.ipv4.ip_forward                 = 1 
        EOF

   - name: Apply sysctl params without reboot.
     command: sysctl --system

   - name: Installing Prerequisites for Kubernetes
     apt: 
       name:
         - apt-transport-https
         - ca-certificates
         - curl
         - gnupg-agent
         - vim
         - software-properties-common
       state: present
       update_cache: true


   - name: Add Google official GPG key
     apt_key:
       url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
       state: present

   - name: Add Kubernetes Repository
     apt_repository:
       repo: deb http://apt.kubernetes.io/ kubernetes-xenial main 
       state: present
       filename: kubernetes
       mode: 0600

   - name: Installing Kubernetes Cluster Packages.
     apt: 
       name:
         - kubeadm={{ kube_version }}
         - kubectl={{ kube_version }}
         - kubelet={{ kube_version }}
       state: present
       
   - name: Install containerd.
     apt: 
       name:
         - docker.io
       state: present

   - name: Configure containerd.
     file:
       path: /etc/containerd
       state: directory

   - name: Configure containerd and CGroup
     shell: |
        /usr/bin/containerd config default > /etc/containerd/config.toml
        sudo sed -i 's/ SystemdCgroup = false/ SystemdCgroup = true/' /etc/containerd/config.toml
     
   - name: Enable containerd service, and start it.
     systemd: 
       name: containerd
       state: restarted
       enabled: yes
       daemon-reload: yes
       
   - name: Enable service kubelet, and enable persistently
     service: 
       name: kubelet
       enabled: yes
